<!DOCTYPE html>
<html lang="en" dir="ltr">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
<meta http-equiv="Content-Script-Type" content="text/javascript">
<meta name="robots" content="noindex">
<title>Export: bookhubdb - thebookhub</title>
<link rel="stylesheet" type="text/css" href="db?file=default.css&amp;version=4.1.0">
<script type="text/javascript" src="db?file=functions.js&amp;version=4.1.0"></script>
<link rel="shortcut icon" type="image/x-icon" href="db?file=favicon.ico&amp;version=4.1.0">
<link rel="apple-touch-icon" href="db?file=favicon.ico&amp;version=4.1.0">

<body class="ltr nojs" style="background-image: url('back.jpg');" onkeydown="bodyKeydown(event);" onclick="bodyClick(event);" onload="verifyVersion('4.1.0');">
<script type="text/javascript">
document.body.className = document.body.className.replace(/ nojs/, ' js');
</script>

<div id="help" class="jush-sql jsonly hidden" onmouseover="helpOpen = 1;" onmouseout="helpMouseout(this, event);"></div>

<div id="content" style="background-image: url('back.jpg');">
<p id="breadcrumb"><a href="db">MySQL</a> &raquo; <a href='db?username=abhinav1995' accesskey='1' title='Alt+Shift+1'>Server</a> &raquo; <a href="db?username=abhinav1995&amp;db=bookhubdb">bookhubdb</a> &raquo; Export
<h2>Export: bookhubdb</h2>

<form action="" method="post">
<table cellspacing="0">
<tr><th>Output<td><label><input type='radio' name='output' value='text' checked>open</label><label><input type='radio' name='output' value='file'>save</label><label><input type='radio' name='output' value='gz'>gzip</label>
<tr><th>Format<td><label><input type='radio' name='format' value='sql' checked>SQL</label><label><input type='radio' name='format' value='csv'>CSV,</label><label><input type='radio' name='format' value='csv;'>CSV;</label><label><input type='radio' name='format' value='tsv'>TSV</label>
<tr><th>Database<td><select name='db_style'><option selected><option>USE<option>DROP+CREATE<option>CREATE</select><label><input type='checkbox' name='routines' value='1' checked>Routines</label><label><input type='checkbox' name='events' value='1' checked>Events</label><tr><th>Tables<td><select name='table_style'><option><option selected>DROP+CREATE<option>CREATE</select><label><input type='checkbox' name='auto_increment' value='1'>Auto Increment</label><label><input type='checkbox' name='triggers' value='1' checked>Triggers</label><tr><th>Data<td><select name='data_style'><option><option>TRUNCATE+INSERT<option selected>INSERT<option>INSERT+UPDATE</select></table>
<p><input type="submit" value="Export">
<input type="hidden" name="token" value="360284:551289">

<table cellspacing="0">
<thead><tr><th style='text-align: left;'><label class='block'><input type='checkbox' id='check-tables' checked onclick='formCheck(this, /^tables\[/);'>Tables</label><th style='text-align: right;'><label class='block'>Data<input type='checkbox' id='check-data' checked onclick='formCheck(this, /^data\[/);'></label></thead>
<tr><td><label class='block'><input type='checkbox' name='tables[]' value='buy' checked onclick="checkboxClick(event, this); formUncheck(&#039;check-tables&#039;);">buy</label><td align='right'><label class='block'><span id='Rows-buy'></span><input type='checkbox' name='data[]' value='buy' checked onclick="checkboxClick(event, this); formUncheck(&#039;check-data&#039;);"></label>
<tr><td><label class='block'><input type='checkbox' name='tables[]' value='list' checked onclick="checkboxClick(event, this); formUncheck(&#039;check-tables&#039;);">list</label><td align='right'><label class='block'><span id='Rows-list'></span><input type='checkbox' name='data[]' value='list' checked onclick="checkboxClick(event, this); formUncheck(&#039;check-data&#039;);"></label>
<tr><td><label class='block'><input type='checkbox' name='tables[]' value='wp_blc_filters' checked onclick="checkboxClick(event, this); formUncheck(&#039;check-tables&#039;);">wp_blc_filters</label><td align='right'><label class='block'><span id='Rows-wp_blc_filters'></span><input type='checkbox' name='data[]' value='wp_blc_filters' checked onclick="checkboxClick(event, this); formUncheck(&#039;check-data&#039;);"></label>
<tr><td><label class='block'><input type='checkbox' name='tables[]' value='wp_blc_instances' checked onclick="checkboxClick(event, this); formUncheck(&#039;check-tables&#039;);">wp_blc_instances</label><td align='right'><label class='block'><span id='Rows-wp_blc_instances'></span><input type='checkbox' name='data[]' value='wp_blc_instances' checked onclick="checkboxClick(event, this); formUncheck(&#039;check-data&#039;);"></label>
<tr><td><label class='block'><input type='checkbox' name='tables[]' value='wp_blc_links' checked onclick="checkboxClick(event, this); formUncheck(&#039;check-tables&#039;);">wp_blc_links</label><td align='right'><label class='block'><span id='Rows-wp_blc_links'></span><input type='checkbox' name='data[]' value='wp_blc_links' checked onclick="checkboxClick(event, this); formUncheck(&#039;check-data&#039;);"></label>
<tr><td><label class='block'><input type='checkbox' name='tables[]' value='wp_blc_synch' checked onclick="checkboxClick(event, this); formUncheck(&#039;check-tables&#039;);">wp_blc_synch</label><td align='right'><label class='block'><span id='Rows-wp_blc_synch'></span><input type='checkbox' name='data[]' value='wp_blc_synch' checked onclick="checkboxClick(event, this); formUncheck(&#039;check-data&#039;);"></label>
<tr><td><label class='block'><input type='checkbox' name='tables[]' value='wp_commentmeta' checked onclick="checkboxClick(event, this); formUncheck(&#039;check-tables&#039;);">wp_commentmeta</label><td align='right'><label class='block'><span id='Rows-wp_commentmeta'></span><input type='checkbox' name='data[]' value='wp_commentmeta' checked onclick="checkboxClick(event, this); formUncheck(&#039;check-data&#039;);"></label>
<tr><td><label class='block'><input type='checkbox' name='tables[]' value='wp_comments' checked onclick="checkboxClick(event, this); formUncheck(&#039;check-tables&#039;);">wp_comments</label><td align='right'><label class='block'><span id='Rows-wp_comments'></span><input type='checkbox' name='data[]' value='wp_comments' checked onclick="checkboxClick(event, this); formUncheck(&#039;check-data&#039;);"></label>
<tr><td><label class='block'><input type='checkbox' name='tables[]' value='wp_duplicator_packages' checked onclick="checkboxClick(event, this); formUncheck(&#039;check-tables&#039;);">wp_duplicator_packages</label><td align='right'><label class='block'><span id='Rows-wp_duplicator_packages'></span><input type='checkbox' name='data[]' value='wp_duplicator_packages' checked onclick="checkboxClick(event, this); formUncheck(&#039;check-data&#039;);"></label>
<tr><td><label class='block'><input type='checkbox' name='tables[]' value='wp_links' checked onclick="checkboxClick(event, this); formUncheck(&#039;check-tables&#039;);">wp_links</label><td align='right'><label class='block'><span id='Rows-wp_links'></span><input type='checkbox' name='data[]' value='wp_links' checked onclick="checkboxClick(event, this); formUncheck(&#039;check-data&#039;);"></label>
<tr><td><label class='block'><input type='checkbox' name='tables[]' value='wp_options' checked onclick="checkboxClick(event, this); formUncheck(&#039;check-tables&#039;);">wp_options</label><td align='right'><label class='block'><span id='Rows-wp_options'></span><input type='checkbox' name='data[]' value='wp_options' checked onclick="checkboxClick(event, this); formUncheck(&#039;check-data&#039;);"></label>
<tr><td><label class='block'><input type='checkbox' name='tables[]' value='wp_postmeta' checked onclick="checkboxClick(event, this); formUncheck(&#039;check-tables&#039;);">wp_postmeta</label><td align='right'><label class='block'><span id='Rows-wp_postmeta'></span><input type='checkbox' name='data[]' value='wp_postmeta' checked onclick="checkboxClick(event, this); formUncheck(&#039;check-data&#039;);"></label>
<tr><td><label class='block'><input type='checkbox' name='tables[]' value='wp_posts' checked onclick="checkboxClick(event, this); formUncheck(&#039;check-tables&#039;);">wp_posts</label><td align='right'><label class='block'><span id='Rows-wp_posts'></span><input type='checkbox' name='data[]' value='wp_posts' checked onclick="checkboxClick(event, this); formUncheck(&#039;check-data&#039;);"></label>
<tr><td><label class='block'><input type='checkbox' name='tables[]' value='wp_pvc_daily' checked onclick="checkboxClick(event, this); formUncheck(&#039;check-tables&#039;);">wp_pvc_daily</label><td align='right'><label class='block'><span id='Rows-wp_pvc_daily'></span><input type='checkbox' name='data[]' value='wp_pvc_daily' checked onclick="checkboxClick(event, this); formUncheck(&#039;check-data&#039;);"></label>
<tr><td><label class='block'><input type='checkbox' name='tables[]' value='wp_pvc_total' checked onclick="checkboxClick(event, this); formUncheck(&#039;check-tables&#039;);">wp_pvc_total</label><td align='right'><label class='block'><span id='Rows-wp_pvc_total'></span><input type='checkbox' name='data[]' value='wp_pvc_total' checked onclick="checkboxClick(event, this); formUncheck(&#039;check-data&#039;);"></label>
<tr><td><label class='block'><input type='checkbox' name='tables[]' value='wp_terms' checked onclick="checkboxClick(event, this); formUncheck(&#039;check-tables&#039;);">wp_terms</label><td align='right'><label class='block'><span id='Rows-wp_terms'></span><input type='checkbox' name='data[]' value='wp_terms' checked onclick="checkboxClick(event, this); formUncheck(&#039;check-data&#039;);"></label>
<tr><td><label class='block'><input type='checkbox' name='tables[]' value='wp_term_relationships' checked onclick="checkboxClick(event, this); formUncheck(&#039;check-tables&#039;);">wp_term_relationships</label><td align='right'><label class='block'><span id='Rows-wp_term_relationships'></span><input type='checkbox' name='data[]' value='wp_term_relationships' checked onclick="checkboxClick(event, this); formUncheck(&#039;check-data&#039;);"></label>
<tr><td><label class='block'><input type='checkbox' name='tables[]' value='wp_term_taxonomy' checked onclick="checkboxClick(event, this); formUncheck(&#039;check-tables&#039;);">wp_term_taxonomy</label><td align='right'><label class='block'><span id='Rows-wp_term_taxonomy'></span><input type='checkbox' name='data[]' value='wp_term_taxonomy' checked onclick="checkboxClick(event, this); formUncheck(&#039;check-data&#039;);"></label>
<tr><td><label class='block'><input type='checkbox' name='tables[]' value='wp_top_ten' checked onclick="checkboxClick(event, this); formUncheck(&#039;check-tables&#039;);">wp_top_ten</label><td align='right'><label class='block'><span id='Rows-wp_top_ten'></span><input type='checkbox' name='data[]' value='wp_top_ten' checked onclick="checkboxClick(event, this); formUncheck(&#039;check-data&#039;);"></label>
<tr><td><label class='block'><input type='checkbox' name='tables[]' value='wp_top_ten_daily' checked onclick="checkboxClick(event, this); formUncheck(&#039;check-tables&#039;);">wp_top_ten_daily</label><td align='right'><label class='block'><span id='Rows-wp_top_ten_daily'></span><input type='checkbox' name='data[]' value='wp_top_ten_daily' checked onclick="checkboxClick(event, this); formUncheck(&#039;check-data&#039;);"></label>
<tr><td><label class='block'><input type='checkbox' name='tables[]' value='wp_usermeta' checked onclick="checkboxClick(event, this); formUncheck(&#039;check-tables&#039;);">wp_usermeta</label><td align='right'><label class='block'><span id='Rows-wp_usermeta'></span><input type='checkbox' name='data[]' value='wp_usermeta' checked onclick="checkboxClick(event, this); formUncheck(&#039;check-data&#039;);"></label>
<tr><td><label class='block'><input type='checkbox' name='tables[]' value='wp_users' checked onclick="checkboxClick(event, this); formUncheck(&#039;check-tables&#039;);">wp_users</label><td align='right'><label class='block'><span id='Rows-wp_users'></span><input type='checkbox' name='data[]' value='wp_users' checked onclick="checkboxClick(event, this); formUncheck(&#039;check-data&#039;);"></label>
<tr><td><label class='block'><input type='checkbox' name='tables[]' value='wp_wfBadLeechers' checked onclick="checkboxClick(event, this); formUncheck(&#039;check-tables&#039;);">wp_wfBadLeechers</label><td align='right'><label class='block'><span id='Rows-wp_wfBadLeechers'></span><input type='checkbox' name='data[]' value='wp_wfBadLeechers' checked onclick="checkboxClick(event, this); formUncheck(&#039;check-data&#039;);"></label>
<tr><td><label class='block'><input type='checkbox' name='tables[]' value='wp_wfBlockedIPLog' checked onclick="checkboxClick(event, this); formUncheck(&#039;check-tables&#039;);">wp_wfBlockedIPLog</label><td align='right'><label class='block'><span id='Rows-wp_wfBlockedIPLog'></span><input type='checkbox' name='data[]' value='wp_wfBlockedIPLog' checked onclick="checkboxClick(event, this); formUncheck(&#039;check-data&#039;);"></label>
<tr><td><label class='block'><input type='checkbox' name='tables[]' value='wp_wfBlocks' checked onclick="checkboxClick(event, this); formUncheck(&#039;check-tables&#039;);">wp_wfBlocks</label><td align='right'><label class='block'><span id='Rows-wp_wfBlocks'></span><input type='checkbox' name='data[]' value='wp_wfBlocks' checked onclick="checkboxClick(event, this); formUncheck(&#039;check-data&#039;);"></label>
<tr><td><label class='block'><input type='checkbox' name='tables[]' value='wp_wfBlocksAdv' checked onclick="checkboxClick(event, this); formUncheck(&#039;check-tables&#039;);">wp_wfBlocksAdv</label><td align='right'><label class='block'><span id='Rows-wp_wfBlocksAdv'></span><input type='checkbox' name='data[]' value='wp_wfBlocksAdv' checked onclick="checkboxClick(event, this); formUncheck(&#039;check-data&#039;);"></label>
<tr><td><label class='block'><input type='checkbox' name='tables[]' value='wp_wfConfig' checked onclick="checkboxClick(event, this); formUncheck(&#039;check-tables&#039;);">wp_wfConfig</label><td align='right'><label class='block'><span id='Rows-wp_wfConfig'></span><input type='checkbox' name='data[]' value='wp_wfConfig' checked onclick="checkboxClick(event, this); formUncheck(&#039;check-data&#039;);"></label>
<tr><td><label class='block'><input type='checkbox' name='tables[]' value='wp_wfCrawlers' checked onclick="checkboxClick(event, this); formUncheck(&#039;check-tables&#039;);">wp_wfCrawlers</label><td align='right'><label class='block'><span id='Rows-wp_wfCrawlers'></span><input type='checkbox' name='data[]' value='wp_wfCrawlers' checked onclick="checkboxClick(event, this); formUncheck(&#039;check-data&#039;);"></label>
<tr><td><label class='block'><input type='checkbox' name='tables[]' value='wp_wfFileMods' checked onclick="checkboxClick(event, this); formUncheck(&#039;check-tables&#039;);">wp_wfFileMods</label><td align='right'><label class='block'><span id='Rows-wp_wfFileMods'></span><input type='checkbox' name='data[]' value='wp_wfFileMods' checked onclick="checkboxClick(event, this); formUncheck(&#039;check-data&#039;);"></label>
<tr><td><label class='block'><input type='checkbox' name='tables[]' value='wp_wfHits' checked onclick="checkboxClick(event, this); formUncheck(&#039;check-tables&#039;);">wp_wfHits</label><td align='right'><label class='block'><span id='Rows-wp_wfHits'></span><input type='checkbox' name='data[]' value='wp_wfHits' checked onclick="checkboxClick(event, this); formUncheck(&#039;check-data&#039;);"></label>
<tr><td><label class='block'><input type='checkbox' name='tables[]' value='wp_wfHoover' checked onclick="checkboxClick(event, this); formUncheck(&#039;check-tables&#039;);">wp_wfHoover</label><td align='right'><label class='block'><span id='Rows-wp_wfHoover'></span><input type='checkbox' name='data[]' value='wp_wfHoover' checked onclick="checkboxClick(event, this); formUncheck(&#039;check-data&#039;);"></label>
<tr><td><label class='block'><input type='checkbox' name='tables[]' value='wp_wfIssues' checked onclick="checkboxClick(event, this); formUncheck(&#039;check-tables&#039;);">wp_wfIssues</label><td align='right'><label class='block'><span id='Rows-wp_wfIssues'></span><input type='checkbox' name='data[]' value='wp_wfIssues' checked onclick="checkboxClick(event, this); formUncheck(&#039;check-data&#039;);"></label>
<tr><td><label class='block'><input type='checkbox' name='tables[]' value='wp_wfLeechers' checked onclick="checkboxClick(event, this); formUncheck(&#039;check-tables&#039;);">wp_wfLeechers</label><td align='right'><label class='block'><span id='Rows-wp_wfLeechers'></span><input type='checkbox' name='data[]' value='wp_wfLeechers' checked onclick="checkboxClick(event, this); formUncheck(&#039;check-data&#039;);"></label>
<tr><td><label class='block'><input type='checkbox' name='tables[]' value='wp_wfLockedOut' checked onclick="checkboxClick(event, this); formUncheck(&#039;check-tables&#039;);">wp_wfLockedOut</label><td align='right'><label class='block'><span id='Rows-wp_wfLockedOut'></span><input type='checkbox' name='data[]' value='wp_wfLockedOut' checked onclick="checkboxClick(event, this); formUncheck(&#039;check-data&#039;);"></label>
<tr><td><label class='block'><input type='checkbox' name='tables[]' value='wp_wfLocs' checked onclick="checkboxClick(event, this); formUncheck(&#039;check-tables&#039;);">wp_wfLocs</label><td align='right'><label class='block'><span id='Rows-wp_wfLocs'></span><input type='checkbox' name='data[]' value='wp_wfLocs' checked onclick="checkboxClick(event, this); formUncheck(&#039;check-data&#039;);"></label>
<tr><td><label class='block'><input type='checkbox' name='tables[]' value='wp_wfLogins' checked onclick="checkboxClick(event, this); formUncheck(&#039;check-tables&#039;);">wp_wfLogins</label><td align='right'><label class='block'><span id='Rows-wp_wfLogins'></span><input type='checkbox' name='data[]' value='wp_wfLogins' checked onclick="checkboxClick(event, this); formUncheck(&#039;check-data&#039;);"></label>
<tr><td><label class='block'><input type='checkbox' name='tables[]' value='wp_wfNet404s' checked onclick="checkboxClick(event, this); formUncheck(&#039;check-tables&#039;);">wp_wfNet404s</label><td align='right'><label class='block'><span id='Rows-wp_wfNet404s'></span><input type='checkbox' name='data[]' value='wp_wfNet404s' checked onclick="checkboxClick(event, this); formUncheck(&#039;check-data&#039;);"></label>
<tr><td><label class='block'><input type='checkbox' name='tables[]' value='wp_wfReverseCache' checked onclick="checkboxClick(event, this); formUncheck(&#039;check-tables&#039;);">wp_wfReverseCache</label><td align='right'><label class='block'><span id='Rows-wp_wfReverseCache'></span><input type='checkbox' name='data[]' value='wp_wfReverseCache' checked onclick="checkboxClick(event, this); formUncheck(&#039;check-data&#039;);"></label>
<tr><td><label class='block'><input type='checkbox' name='tables[]' value='wp_wfScanners' checked onclick="checkboxClick(event, this); formUncheck(&#039;check-tables&#039;);">wp_wfScanners</label><td align='right'><label class='block'><span id='Rows-wp_wfScanners'></span><input type='checkbox' name='data[]' value='wp_wfScanners' checked onclick="checkboxClick(event, this); formUncheck(&#039;check-data&#039;);"></label>
<tr><td><label class='block'><input type='checkbox' name='tables[]' value='wp_wfStatus' checked onclick="checkboxClick(event, this); formUncheck(&#039;check-tables&#039;);">wp_wfStatus</label><td align='right'><label class='block'><span id='Rows-wp_wfStatus'></span><input type='checkbox' name='data[]' value='wp_wfStatus' checked onclick="checkboxClick(event, this); formUncheck(&#039;check-data&#039;);"></label>
<tr><td><label class='block'><input type='checkbox' name='tables[]' value='wp_wfThrottleLog' checked onclick="checkboxClick(event, this); formUncheck(&#039;check-tables&#039;);">wp_wfThrottleLog</label><td align='right'><label class='block'><span id='Rows-wp_wfThrottleLog'></span><input type='checkbox' name='data[]' value='wp_wfThrottleLog' checked onclick="checkboxClick(event, this); formUncheck(&#039;check-data&#039;);"></label>
<tr><td><label class='block'><input type='checkbox' name='tables[]' value='wp_wfVulnScanners' checked onclick="checkboxClick(event, this); formUncheck(&#039;check-tables&#039;);">wp_wfVulnScanners</label><td align='right'><label class='block'><span id='Rows-wp_wfVulnScanners'></span><input type='checkbox' name='data[]' value='wp_wfVulnScanners' checked onclick="checkboxClick(event, this); formUncheck(&#039;check-data&#039;);"></label>
<script type='text/javascript'>ajaxSetHtml('db?username=abhinav1995&db=bookhubdb&script=db');</script>
</table>
</form>
<p><a href='db?username=abhinav1995&amp;db=bookhubdb&amp;dump=wp%25'>wp</a></div>

<form action="" method="post">
<p class="logout">
<input type="submit" name="logout" value="Logout" id="logout">
<input type="hidden" name="token" value="360284:551289">
</p>
</form>
<div id="menu">
<h1>
<a href='http:/thebookhub.in/' target='_blank' id='h1'>thebookhub</a> <span class="version">4.1.0</span>
<a href="http:/thebookhub.in/#download" target="_blank" id="version"></a>
</h1>
<script type="text/javascript" src="db?file=jush.js&amp;version=4.1.0"></script>
<script type="text/javascript">
var jushLinks = { sql: [ 'db?username=abhinav1995&db=bookhubdb&table=$&', /\b(buy|list|wp_blc_filters|wp_blc_instances|wp_blc_links|wp_blc_synch|wp_commentmeta|wp_comments|wp_duplicator_packages|wp_links|wp_options|wp_postmeta|wp_posts|wp_pvc_daily|wp_pvc_total|wp_terms|wp_term_relationships|wp_term_taxonomy|wp_top_ten|wp_top_ten_daily|wp_usermeta|wp_users|wp_wfBadLeechers|wp_wfBlockedIPLog|wp_wfBlocks|wp_wfBlocksAdv|wp_wfConfig|wp_wfCrawlers|wp_wfFileMods|wp_wfHits|wp_wfHoover|wp_wfIssues|wp_wfLeechers|wp_wfLockedOut|wp_wfLocs|wp_wfLogins|wp_wfNet404s|wp_wfReverseCache|wp_wfScanners|wp_wfStatus|wp_wfThrottleLog|wp_wfVulnScanners)\b/g ] };
jushLinks.bac = jushLinks.sql;
jushLinks.bra = jushLinks.sql;
jushLinks.sqlite_quo = jushLinks.sql;
jushLinks.mssql_bra = jushLinks.sql;
bodyLoad('5.5');
</script>
<form action="">
<p id="dbs">
<input type="hidden" name="username" value="abhinav1995"><span title='database'>DB</span>: <select name='db' onmousedown='dbMouseDown(event, this);' onchange='dbChange(this);'><option value=""><option>information_schema<option selected>bookhubdb</select><input type='submit' value='Use' class='hidden'>
<input type="hidden" name="dump" value=""></p></form>
<p class='links'><a href='db?username=abhinav1995&amp;db=bookhubdb&amp;sql='>SQL command</a>
<a href='db?username=abhinav1995&amp;db=bookhubdb&amp;import='>Import</a>
<a href='db?username=abhinav1995&amp;db=bookhubdb&amp;dump=' id='dump' class='active '>Dump</a>
<a href="db?username=abhinav1995&amp;db=bookhubdb&amp;create=">Create table</a>
<p id='tables' onmouseover='menuOver(this, event);' onmouseout='menuOut(this);'>
<a href="db?username=abhinav1995&amp;db=bookhubdb&amp;select=buy">select</a> <a href="db?username=abhinav1995&amp;db=bookhubdb&amp;table=buy" title='Show structure'>buy</a><br>
<a href="db?username=abhinav1995&amp;db=bookhubdb&amp;select=list">select</a> <a href="db?username=abhinav1995&amp;db=bookhubdb&amp;table=list" title='Show structure'>list</a><br>
<a href="db?username=abhinav1995&amp;db=bookhubdb&amp;select=wp_blc_filters">select</a> <a href="db?username=abhinav1995&amp;db=bookhubdb&amp;table=wp_blc_filters" title='Show structure'>wp_blc_filters</a><br>
<a href="db?username=abhinav1995&amp;db=bookhubdb&amp;select=wp_blc_instances">select</a> <a href="db?username=abhinav1995&amp;db=bookhubdb&amp;table=wp_blc_instances" title='Show structure'>wp_blc_instances</a><br>
<a href="db?username=abhinav1995&amp;db=bookhubdb&amp;select=wp_blc_links">select</a> <a href="db?username=abhinav1995&amp;db=bookhubdb&amp;table=wp_blc_links" title='Show structure'>wp_blc_links</a><br>
<a href="db?username=abhinav1995&amp;db=bookhubdb&amp;select=wp_blc_synch">select</a> <a href="db?username=abhinav1995&amp;db=bookhubdb&amp;table=wp_blc_synch" title='Show structure'>wp_blc_synch</a><br>
<a href="db?username=abhinav1995&amp;db=bookhubdb&amp;select=wp_commentmeta">select</a> <a href="db?username=abhinav1995&amp;db=bookhubdb&amp;table=wp_commentmeta" title='Show structure'>wp_commentmeta</a><br>
<a href="db?username=abhinav1995&amp;db=bookhubdb&amp;select=wp_comments">select</a> <a href="db?username=abhinav1995&amp;db=bookhubdb&amp;table=wp_comments" title='Show structure'>wp_comments</a><br>
<a href="db?username=abhinav1995&amp;db=bookhubdb&amp;select=wp_duplicator_packages">select</a> <a href="db?username=abhinav1995&amp;db=bookhubdb&amp;table=wp_duplicator_packages" title='Show structure'>wp_duplicator_packages</a><br>
<a href="db?username=abhinav1995&amp;db=bookhubdb&amp;select=wp_links">select</a> <a href="db?username=abhinav1995&amp;db=bookhubdb&amp;table=wp_links" title='Show structure'>wp_links</a><br>
<a href="db?username=abhinav1995&amp;db=bookhubdb&amp;select=wp_options">select</a> <a href="db?username=abhinav1995&amp;db=bookhubdb&amp;table=wp_options" title='Show structure'>wp_options</a><br>
<a href="db?username=abhinav1995&amp;db=bookhubdb&amp;select=wp_postmeta">select</a> <a href="db?username=abhinav1995&amp;db=bookhubdb&amp;table=wp_postmeta" title='Show structure'>wp_postmeta</a><br>
<a href="db?username=abhinav1995&amp;db=bookhubdb&amp;select=wp_posts">select</a> <a href="db?username=abhinav1995&amp;db=bookhubdb&amp;table=wp_posts" title='Show structure'>wp_posts</a><br>
<a href="db?username=abhinav1995&amp;db=bookhubdb&amp;select=wp_pvc_daily">select</a> <a href="db?username=abhinav1995&amp;db=bookhubdb&amp;table=wp_pvc_daily" title='Show structure'>wp_pvc_daily</a><br>
<a href="db?username=abhinav1995&amp;db=bookhubdb&amp;select=wp_pvc_total">select</a> <a href="db?username=abhinav1995&amp;db=bookhubdb&amp;table=wp_pvc_total" title='Show structure'>wp_pvc_total</a><br>
<a href="db?username=abhinav1995&amp;db=bookhubdb&amp;select=wp_terms">select</a> <a href="db?username=abhinav1995&amp;db=bookhubdb&amp;table=wp_terms" title='Show structure'>wp_terms</a><br>
<a href="db?username=abhinav1995&amp;db=bookhubdb&amp;select=wp_term_relationships">select</a> <a href="db?username=abhinav1995&amp;db=bookhubdb&amp;table=wp_term_relationships" title='Show structure'>wp_term_relationships</a><br>
<a href="db?username=abhinav1995&amp;db=bookhubdb&amp;select=wp_term_taxonomy">select</a> <a href="db?username=abhinav1995&amp;db=bookhubdb&amp;table=wp_term_taxonomy" title='Show structure'>wp_term_taxonomy</a><br>
<a href="db?username=abhinav1995&amp;db=bookhubdb&amp;select=wp_top_ten">select</a> <a href="db?username=abhinav1995&amp;db=bookhubdb&amp;table=wp_top_ten" title='Show structure'>wp_top_ten</a><br>
<a href="db?username=abhinav1995&amp;db=bookhubdb&amp;select=wp_top_ten_daily">select</a> <a href="db?username=abhinav1995&amp;db=bookhubdb&amp;table=wp_top_ten_daily" title='Show structure'>wp_top_ten_daily</a><br>
<a href="db?username=abhinav1995&amp;db=bookhubdb&amp;select=wp_usermeta">select</a> <a href="db?username=abhinav1995&amp;db=bookhubdb&amp;table=wp_usermeta" title='Show structure'>wp_usermeta</a><br>
<a href="db?username=abhinav1995&amp;db=bookhubdb&amp;select=wp_users">select</a> <a href="db?username=abhinav1995&amp;db=bookhubdb&amp;table=wp_users" title='Show structure'>wp_users</a><br>
<a href="db?username=abhinav1995&amp;db=bookhubdb&amp;select=wp_wfBadLeechers">select</a> <a href="db?username=abhinav1995&amp;db=bookhubdb&amp;table=wp_wfBadLeechers" title='Show structure'>wp_wfBadLeechers</a><br>
<a href="db?username=abhinav1995&amp;db=bookhubdb&amp;select=wp_wfBlockedIPLog">select</a> <a href="db?username=abhinav1995&amp;db=bookhubdb&amp;table=wp_wfBlockedIPLog" title='Show structure'>wp_wfBlockedIPLog</a><br>
<a href="db?username=abhinav1995&amp;db=bookhubdb&amp;select=wp_wfBlocks">select</a> <a href="db?username=abhinav1995&amp;db=bookhubdb&amp;table=wp_wfBlocks" title='Show structure'>wp_wfBlocks</a><br>
<a href="db?username=abhinav1995&amp;db=bookhubdb&amp;select=wp_wfBlocksAdv">select</a> <a href="db?username=abhinav1995&amp;db=bookhubdb&amp;table=wp_wfBlocksAdv" title='Show structure'>wp_wfBlocksAdv</a><br>
<a href="db?username=abhinav1995&amp;db=bookhubdb&amp;select=wp_wfConfig">select</a> <a href="db?username=abhinav1995&amp;db=bookhubdb&amp;table=wp_wfConfig" title='Show structure'>wp_wfConfig</a><br>
<a href="db?username=abhinav1995&amp;db=bookhubdb&amp;select=wp_wfCrawlers">select</a> <a href="db?username=abhinav1995&amp;db=bookhubdb&amp;table=wp_wfCrawlers" title='Show structure'>wp_wfCrawlers</a><br>
<a href="db?username=abhinav1995&amp;db=bookhubdb&amp;select=wp_wfFileMods">select</a> <a href="db?username=abhinav1995&amp;db=bookhubdb&amp;table=wp_wfFileMods" title='Show structure'>wp_wfFileMods</a><br>
<a href="db?username=abhinav1995&amp;db=bookhubdb&amp;select=wp_wfHits">select</a> <a href="db?username=abhinav1995&amp;db=bookhubdb&amp;table=wp_wfHits" title='Show structure'>wp_wfHits</a><br>
<a href="db?username=abhinav1995&amp;db=bookhubdb&amp;select=wp_wfHoover">select</a> <a href="db?username=abhinav1995&amp;db=bookhubdb&amp;table=wp_wfHoover" title='Show structure'>wp_wfHoover</a><br>
<a href="db?username=abhinav1995&amp;db=bookhubdb&amp;select=wp_wfIssues">select</a> <a href="db?username=abhinav1995&amp;db=bookhubdb&amp;table=wp_wfIssues" title='Show structure'>wp_wfIssues</a><br>
<a href="db?username=abhinav1995&amp;db=bookhubdb&amp;select=wp_wfLeechers">select</a> <a href="db?username=abhinav1995&amp;db=bookhubdb&amp;table=wp_wfLeechers" title='Show structure'>wp_wfLeechers</a><br>
<a href="db?username=abhinav1995&amp;db=bookhubdb&amp;select=wp_wfLockedOut">select</a> <a href="db?username=abhinav1995&amp;db=bookhubdb&amp;table=wp_wfLockedOut" title='Show structure'>wp_wfLockedOut</a><br>
<a href="db?username=abhinav1995&amp;db=bookhubdb&amp;select=wp_wfLocs">select</a> <a href="db?username=abhinav1995&amp;db=bookhubdb&amp;table=wp_wfLocs" title='Show structure'>wp_wfLocs</a><br>
<a href="db?username=abhinav1995&amp;db=bookhubdb&amp;select=wp_wfLogins">select</a> <a href="db?username=abhinav1995&amp;db=bookhubdb&amp;table=wp_wfLogins" title='Show structure'>wp_wfLogins</a><br>
<a href="db?username=abhinav1995&amp;db=bookhubdb&amp;select=wp_wfNet404s">select</a> <a href="db?username=abhinav1995&amp;db=bookhubdb&amp;table=wp_wfNet404s" title='Show structure'>wp_wfNet404s</a><br>
<a href="db?username=abhinav1995&amp;db=bookhubdb&amp;select=wp_wfReverseCache">select</a> <a href="db?username=abhinav1995&amp;db=bookhubdb&amp;table=wp_wfReverseCache" title='Show structure'>wp_wfReverseCache</a><br>
<a href="db?username=abhinav1995&amp;db=bookhubdb&amp;select=wp_wfScanners">select</a> <a href="db?username=abhinav1995&amp;db=bookhubdb&amp;table=wp_wfScanners" title='Show structure'>wp_wfScanners</a><br>
<a href="db?username=abhinav1995&amp;db=bookhubdb&amp;select=wp_wfStatus">select</a> <a href="db?username=abhinav1995&amp;db=bookhubdb&amp;table=wp_wfStatus" title='Show structure'>wp_wfStatus</a><br>
<a href="db?username=abhinav1995&amp;db=bookhubdb&amp;select=wp_wfThrottleLog">select</a> <a href="db?username=abhinav1995&amp;db=bookhubdb&amp;table=wp_wfThrottleLog" title='Show structure'>wp_wfThrottleLog</a><br>
<a href="db?username=abhinav1995&amp;db=bookhubdb&amp;select=wp_wfVulnScanners">select</a> <a href="db?username=abhinav1995&amp;db=bookhubdb&amp;table=wp_wfVulnScanners" title='Show structure'>wp_wfVulnScanners</a><br>
</div>
<script type="text/javascript">setupSubmitHighlight(document);</script>
